Front lk
KayotPoziloy/thematic_audio_player pull request #92
Opened 2024-12-05 15:24 UTC by xXxILiaxXx

## Type
* [x] new
* [ ] fix
## Interface
* [ ] frontend
* [ ] backend
* [x] ci
## Tests
* [ ] e2e
* [ ] unit
* [ ] lint
## Links 

## Description

Добавление ЛК в основной проект:
1. Основная страница личного кабинет
2. Второстепенные страницы личного кабинета 
3. Настройка маршрутов 
4. Оформление

2024-12-05 20:31 UTC, Aidar042002 approved these changes

2024-12-06 15:31 UTC, KayotPoziloy commented
Для всех изображений есть директория /public

2024-12-06 15:36 UTC, KayotPoziloy commented
![{A8DBA1B6-60B2-4FCA-91C0-E6AFEC0A8F4D}](https://github.com/user-attachments/assets/7434f309-ad16-4e16-9146-99d3536265f6)
при нажатии на кнопку зарегистрироваться ничего не происходит

2024-12-06 15:40 UTC, KayotPoziloy commented
![{BCBBEF55-9BA6-4838-8865-C6F17B09DED7}](https://github.com/user-attachments/assets/b8ab739a-8471-41fc-a819-499433c7bc2e)
при выборе плейлиста ничего не происходит

2024-12-06 16:00 UTC, KayotPoziloy requested changes

2024-12-06 17:29 UTC, xXxILiaxXx commented on frontend/src/components/Acc_components/Privacy.tsx
> +                «Условия использования сервиса ThematiaсAudioPlaer», размещенные в сети Интернет по адресу: https://github.com/KayotPoziloy/thematic_audio_player, а также документы ООО «ThematiaсAudi
Исправил

2024-12-06 17:29 UTC, xXxILiaxXx commented on frontend/src/components/Acc_components/Privacy.tsx
Исправил

2024-12-06 17:57 UTC, xXxILiaxXx commented on frontend/src/App.tsx
> -                        <p>Выберите плейлист</p>
Для того, чтобы фон, находящийся и исходящий с этой страницы, а как следствие монтирующийся и в ЛК, был позади второстепенных элементов остальных страниц. До изменения часть объектов просто загораживалась фоном, причем работало это не всегда однотипно, потому стилями это не фиксилось.

2024-12-07 14:48 UTC, Kkjss90 approved these changes

2024-12-07 16:23 UTC, xXxILiaxXx commented
The last commit -- new radio statin

2024-12-07 20:36 UTC, et-yula approved these changes

2024-12-08 15:44 UTC, KayotPoziloy approved these changes

2024-12-08 15:45 UTC, merged